### ISSUE TITLE
This repo seems to be abandoned

### ISSUE THREAD

**Issue by ebothmann** [davidchall/homebrew-hep#144]
Dear all,

There was no maintaining of this repo since ~10 months ago. This is unfortunate, because I think it has proved to be very useful. Thanks @davidchall for all your efforts and for starting this in the first place!

@davidchall Could you please comment on whether you still intend to maintain this repo? If not we might think about appointing new maintainers for this repo, or we could do active maintaining in some fork and leave a notification on the top this repo’s README to give a link to the "official" fork.

In any case, I'm interested in contributing. However, I'm only using a few formulae myself actively, so we might want to share the effort. I looked through the fork list, @jarb2, @MasonGao and @papucci seem to have forks that are more recently updated then this one. Maybe they are also interested in keeping this up.

Best regards,
  Enrico

**Comment by davidchall** [comment]
Hi @ebothmann,

You're absolutely right and I apologize for my lack of communication on this.

I actually left high energy physics at the end of 2014, but kept supporting homebrew-hep in my spare time as a form of community service. However, over the years I grew frustrated that most of the maintenance work was caused by the instability of the Homebrew formula syntax instead of actual package updates. I also now have more demands on my time, so it's become more and more difficult to find time to devote to this repo.

I'm happy to hear that homebrew-hep is still proving useful to the HEP community though, and would love for it to still be actively maintained. I'll certainly add you @ebothmann as a maintainer. I also know that @cjohnson-phys and @nhartland have historically contributed significantly, so would they also like to be added as maintainers?

Cheers,
David

**Comment by ebothmann** [comment]
Hi @davidchall,

In this case, thanks for keeping it alive for ~4 more years even though you left!!

@cjohnson-phys it's cool that you join, too; hopefully as users we cover a good subset of the formulae.

Let's get to work 🚂 

Cheers,
  Enrico

**Comment by nhartland** [comment]
Hi @davidchall 

Thanks for the mention, but I've now (very recently) also left the field.
In any case, thanks for creating and maintaining the repo, it has been an enormous help.

Cheers,
Nathan
