### ISSUE TITLE
missing package for fastjet

### ISSUE THREAD

**Issue by wyd1216** [davidchall/homebrew-hep#160]
### Indicate troubleshooting steps taken

 - [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors, tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
Failed to download resource "fastjet"
#### The complete command that you issued:
brew install fastjet
#### Output of `brew config`:
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fastjet"
Download failed: https://dl.bintray.com/davidchall/bottles-hep/fastjet-3.3.2.high_sierra.bottle.tar.gz

**Comment by ebothmann** [comment]
Hi @wyd1216,

although I'm not exactly sure what the issue is, you can probably do `brew install -s fastjet` to force brew to build from source.

The bottles (pre-compiled packages) are not maintained anymore (but still seem to be used if someone uses High Sierra or below). Feel free to submit a PR to disable for homebrew-hep (or better yet: fix it).

Hope that helps,
 eno

**Comment by wyd1216** [comment]
Thank you @ebothmann ,
 
My problem is solved.
