### ISSUE TITLE
Trying to install herwig and sherpa but failed

### ISSUE THREAD

**Issue by Mughal789** [davidchall/homebrew-hep#180]
I am trying to install herwig++ but failed and getting this error (even i have python installed already):

🍺  /usr/local/Cellar/lhapdf/6.2.1: 42 files, 2.5MB, built in 1 minute 6 seconds
==> Installing davidchall/hep/herwig dependency: yoda
==> ./configure --prefix=/usr/local/Cellar/yoda/1.6.7
Last 15 lines from /Users/AAA/Library/Logs/Homebrew/yoda/01.configure:
checking python extra linking flags... 
checking consistency of all components of python development environment... no
configure: error: in `/private/tmp/yoda-20211120-28642-86t4gu/YODA-1.6.7':
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

See `config.log' for more details

The other error i am getting while installing sherpa which is :
🍺  /usr/local/Cellar/scons/4.3.0: 2,105 files, 27.0MB
==> Installing davidchall/hep/sherpa dependency: openloops
==> Patching
==> scons
Last 15 lines from /Users/AAA/Library/Logs/Homebrew/openloops/01.scons:
2021-11-20 09:49:38 +0000

scons

scons: Reading SConscript files ...
  File "/private/tmp/openloops-20211120-31392-1sod3lj/OpenLoops-1.3.1/SConstruct", line 93

    print help_message

    ^^^^^^^^^^^^^^^^^^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by ebothmann** [comment]
Hm, the latter is clearly from a `python3` trying to run `python2` code. It's difficult to help you remotely, as these things are usually highly dependent on the system setup and what you did to your python environment.

In any case, perhaps this can be fixed by adding explicit dependencies to the recipes, such that `brew` can sort it out without relying on implicit expectations about the host system. Unfortunately I can not look into this right now. For what it's worth, I plan to upgrade my toolchain in a few weeks and then I'll double-check that `sherpa` installs properly using `brew`.

If you need to get it running now, you might need to try and fix the issue yourself, or fall back on installing the tools manually.

**Comment by davidchall** [comment]
@Mughal789 - I've update the herwig and sherpa formulae. Could you please try again?
