### ISSUE TITLE
Linking homebrew installed Sherpa to OpenLoops

### ISSUE THREAD

**Issue by SimoAlx** [davidchall/homebrew-hep#50]
Is there any possible way of rebuilding Sherpa with OpenLoops, if installed via homebrew? The usual way is to use autoreconf, and rebuild using ./configure with --enable-openloops=path/to/openloops, but there is not ./configure with Sherpa installed through homebrew. Is there any possible way of doing this?

**Comment by ebothmann** [comment]
Hi Alex,

First of all, there is not yet a formula for OpenLoops (though it should be relatively straightforward to create one). The next step would be to add the option to link with OpenLoops to the Sherpa formula (cf. `brew info sherpa` for a list of available options and `brew edit sherpa` to see how that translates to the formula.).

There are formula cookbooks and pretty good documentation out there from the homebrew guys on how to create/edit formulae.

Cheers,
eno

**Comment by veprbl** [comment]
Unfortunately, the current Sherpa formula doesn't support OpenLoops. In order to add that, we would need a generic way to detect the OpenLoops installation path. Normally this is done by creating a formula for OpenLoops itself, so it is installed by homebrew and that way it's installation path is easily tracked with homebrews internal mechanisms. However, we don't have that formula just yet, somebody must produce it first.

For now you could edit your Sherpa formula locally using ```brew edit sherpa``` to set your specific path manually:
```diff
--- a/sherpa.rb
+++ b/sherpa.rb
@@ -38,6 +38,7 @@ class Sherpa < Formula
     args << "--enable-lhapdf=#{Formula['lhapdf'].prefix}"   if build.with? "lhapdf"
     args << "--enable-fastjet=#{Formula['fastjet'].prefix}" if build.with? "fastjet"
     args << "--enable-root=#{Formula['root'].prefix}"       if build.with? "root"
+    args << "--enable-openloops=path/to/openloops"
 
     if build.with? "mcfm"
       mcfm_path = buildpath/'mcfm'
```
This is an ugly way, but gives the result immediately.

**Comment by davidchall** [comment]
There is now an openloops formula, and the sherpa formula now has a --with-openloops option.
