### ISSUE TITLE
`brew audit sherpa.rb` raises error

### ISSUE THREAD

**Issue by ebothmann** [davidchall/homebrew-hep#81]
With the current formula, I get

```
❯ brew audit sherpa.rb
sherpa:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "davidchall/hep/fastjet" => :linked
Error: 1 problem in 1 formula
```

Adding the proposed line lets the error disappear. But there is an optional dependency declared already, and also why does it only complain about `fastjet`. I also can not find s.th. via a quick Web search. Does anyone know how to correctly set it up the homebrew-way?

**Comment by davidchall** [comment]
Perhaps homebrew is complaining because `fastjet` was not compiled with the C++11 standard? (Though I would expect this problem with other dependencies too, like `hepmc`).

Homebrew does have a standard way to track C++11 in dependencies called `:cxx11`. You can see how some different packages are using it [here](https://github.com/Homebrew/homebrew-science/search?utf8=✓&q=cxx11).

It might also be possible to use `cxxstdlib_check :skip` to avoid the gcc stdlib warning, as we do in the `herwig` package.

Sorry that I don't really have time to follow up on this, but this is the route I would follow.

**Comment by veprbl** [comment]
I don't have that on my system. Maybe check what's in your ```otool -L /usr/local/Cellar/sherpa/2.2.1/bin/Sherpa```.

**Comment by ebothmann** [comment]
Somehow, this issue has resolved itself. It was probably specific to my setup at the time.

Regarding the C++11 dependence, looking through your link, I hoped adding `needs :cxx11` to the rivet formula would propagate this to the sherpa installation. But it seems it doesn't work like this. So the only thing we could do now is to replace `ENV.append "CXXFLAGS", "-std=c++11"` in the sherpa formula with `ENV.cxx11`, I suppose. It's always hard to find homebrew documentation, it seems :(
